### ISSUE TITLE
Error when using with customized AUTH_USER_MODEL

### ISSUE THREAD

**Issue by jslootbeek** [drager/django-simple-blog#4]
Django 1.7 with a custom user model defined as settings.AUTH_USER_MODEL throws the following error. I can likely submit a pull-request to fix this in the next few weeks.

simpleblog.Comment.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
simpleblog.Post.posted_by: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

**Comment by drager** [comment]
Fixed in #6
