### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by EmadMokhtar** [drager/django-simple-blog#8]
Can you please update the pypi package? Anyone will pip the app will get the old version.

it's from 2014, please [check here](https://pypi.python.org/pypi/django-simple-blog)

**Comment by drager** [comment]
Will do!

**Comment by drager** [comment]
@EmadMokhtar: It's now published, https://pypi.python.org/pypi/django-simple-blog/0.2.0

**Comment by JHei** [comment]
The pypi package does not contain the migrations folder.

**Comment by drager** [comment]
@JHei: Hmm, I see. I can look into that tomorrow.

**Comment by drager** [comment]
@JHei: Fixed in https://github.com/drager/django-simple-blog/commit/9c2ef7148054805b8603e6e3bdae2cc302d27610 - https://pypi.python.org/pypi/django-simple-blog/0.2.1
